# ── Shell ──────────────────────────────────────────────────
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

# ── Git ────────────────────────────────────────────────────
brew "git"

# ── Runtimes ───────────────────────────────────────────────
brew "fnm"
